### ISSUE TITLE
Кнопка

### ISSUE THREAD

**Issue by scandy5** [AlenaLoik/Crypto#2]
Твоя: 
![image](https://user-images.githubusercontent.com/41551315/57138648-e6342600-6dbb-11e9-9843-398211a8bc78.png)
В макете: 
![image](https://user-images.githubusercontent.com/41551315/57138657-f1875180-6dbb-11e9-862a-a64cd3bb2a88.png)
Она не такого размера и не убран border

**Comment by AlenaLoik** [comment]
Fixed

**Comment by scandy5** [comment]
Не-а, не фиксед. Текст не такой, оно там слитно написано, внимательно присмотрись, и бордер не убран. Напиши в кнопку border: none;

**Comment by AlenaLoik** [comment]
А тепер?

**Comment by AlenaLoik** [comment]
Виправила.

нд, 5 трав. 2019 о 15:52 Sergey <notifications@github.com> пише:
