### ISSUE TITLE
Форма отличается от той, что в макете

### ISSUE THREAD

**Issue by scandy5** [AlenaLoik/Crypto#4]
Твоя:
![image](https://user-images.githubusercontent.com/41551315/57139038-d832d500-6dbc-11e9-8bef-0d7b799846a0.png)
Та что в макете: 
![image](https://user-images.githubusercontent.com/41551315/57139089-fa2c5780-6dbc-11e9-8105-d4b958114271.png)

**Comment by AlenaLoik** [comment]
Fixed
